server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbgreet?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: service-greeting
